import { StyleSheet } from "react-native";

export const styles= StyleSheet.create({
    container:{
        flex:1,
        backgroundColor:'#38A690'
    },
    containerLogo:{
        flex:2,
        backgroundColor:'#38A690',
        justifyContent:'center',
        alignItems:'center'
    },
    containerform:{
        flex:1,
        backgroundColor:'#fff',
        borderTopLeftRadius:25,
        borderTopRightRadius:25,
        paddingStart:'5%',
        paddingEnd:'5%',
        alignItems:'center'
    },
    title:{
        fontSize:24,
        fontWeight:'bold',
        marginTop:28,
        marginBottom:12,
    },
    text:{
        color:'#a1a1a1'
    },
    button:{
        position:'absolute',
        backgroundColor:'#38A690',
        borderRadius:50,
        paddingVertical:8,
        width:'60%',
        alignSelf:'center',
        bottom:'15%',
        alignItems:'center',
        justifyContent:'center'
    },
    buttonText:{
        fontSize:18,
        color:'#fff',
        fontWeight:'bold'
    }
})